### ISSUE TITLE
A better way to build password-less connection 

### ISSUE THREAD

**Issue by XD-DENG** [chinyong-lim/Linux-Unix#1]
Please refer to my repo: [https://github.com/XD-DENG/DIY-A-Cluster/blob/master/chapters/network_basics.md#how-to-set-password-less-access](https://github.com/XD-DENG/DIY-A-Cluster/blob/master/chapters/network_basics.md#how-to-set-password-less-access)

We can use function `ssh-copy-id ID@remote_IP`. It will copy the public key to the remote server and insert it into corresponding file. We don't have to manually copy-paste or manually create file `~/.ssh/authorized_keys`.

**Comment by chinyong-lim** [comment]
@XD-DENG Thanks a lot for your suggestion!!!

**Comment by chinyong-lim** [comment]
@XD-DENG Added the changes here.
https://github.com/chinyong-lim/Linux-Unix/commit/443580f24e745f227989905d6b4c2e9fc9fe6700
